#include "ginfer/engine.h"

#include "artifact/reader.h"

#include <cstdint>
#include <cstdlib>
#include <exception>
#include <iostream>
#include <stdexcept>
#include <utility>
#include <vector>

namespace {

ginfer::EngineOptions engine_options(const char* artifact) {
    ginfer::EngineOptions options;
    options.artifact_path            = artifact;
    options.max_context              = 2304;
    options.kv_capacity              = ginfer::KvCapacityPolicy::explicit_capacity(2304);
    // DFlash executes oversized public chunks as cyclic-cache-sized internal chunks.
    options.prefill_chunk            = 4096;
    options.kv_cache                 = ginfer::KvCacheStorage::BFloat16;
    options.speculative.backend      = ginfer::SpeculativeBackend::DFlash;
    options.speculative.draft_tokens = 1;
    options.use_cuda_graph           = false;
    return options;
}

ginfer::RequestOptions greedy_options(bool reuse, std::uint32_t output_tokens = 1) {
    ginfer::RequestOptions options;
    options.execution.requested_output_tokens = output_tokens;
    options.execution.sampling.temperature    = 0.0F;
    options.execution.allow_prefix_reuse      = reuse;
    options.stop.include_model_defaults       = false;
    return options;
}

ginfer::RequestOptions prefix_options(bool reuse) {
    ginfer::RequestOptions options = greedy_options(reuse);
    options.stop.token_ids         = {0};
    return options;
}

bool one_token_terminal(const ginfer::GenerationResult& result) {
    return result.generated_token_ids.size() == 1 &&
           (result.finish_reason == ginfer::FinishReason::OutputLimit ||
            result.finish_reason == ginfer::FinishReason::StopToken);
}

std::vector<ginfer::TokenId> protocol_prompt(std::size_t token_count) {
    // A real ATEM-shaped prompt keeps generated bytes representative while allowing the test to
    // place the cyclic-cache frontier at an exact token position. The ordinary body token is the
    // checkpoint's leading-space " hello" piece.
    constexpr ginfer::TokenId kBeginOfText = 200000;
    constexpr ginfer::TokenId kStart       = 200022;
    constexpr ginfer::TokenId kMessage     = 200023;
    constexpr ginfer::TokenId kEndOfTurn   = 200008;
    constexpr ginfer::TokenId kUser        = 1556;
    constexpr ginfer::TokenId kAssistant   = 140680;
    constexpr ginfer::TokenId kBody        = 47244;
    constexpr std::size_t kFramingTokens   = 7;

    if (token_count < kFramingTokens) { throw std::logic_error("ATEM prompt is too short"); }
    std::vector<ginfer::TokenId> prompt;
    prompt.reserve(token_count);
    prompt.insert(prompt.end(), {kBeginOfText, kStart, kUser, kMessage});
    prompt.insert(prompt.end(), token_count - kFramingTokens, kBody);
    prompt.insert(prompt.end(), {kEndOfTurn, kStart, kAssistant});
    return prompt;
}

int exercise_cyclic_prefix_boundary(ginfer::Engine& engine) {
    constexpr std::size_t kWrappedPromptTokens = 2050;
    std::vector<ginfer::TokenId> prompt = protocol_prompt(kWrappedPromptTokens);

    const ginfer::GenerationResult first =
        engine.generate(engine.prepare_tokens(prompt), prefix_options(false));
    if (!one_token_terminal(first) || first.reused_prompt_tokens != 0) {
        std::cerr << "Muse DFlash setup request did not establish a retained wrapped frontier: "
                  << "generated=" << first.generated_token_ids.size()
                  << ", finish=" << static_cast<int>(first.finish_reason)
                  << ", reused=" << first.reused_prompt_tokens << '\n';
        return 1;
    }

    const ginfer::GenerationResult identical =
        engine.generate(engine.prepare_tokens(prompt), prefix_options(true));
    if (identical.generated_token_ids.size() != 1 || identical.reused_prompt_tokens != 0 ||
        identical.prefix_reuse_path != ginfer::PrefixReusePath::FullReset) {
        std::cerr << "Muse DFlash rewound a wrapped cyclic frontier: reused="
                  << identical.reused_prompt_tokens << '\n';
        return 1;
    }

    prompt.insert(prompt.end(), first.generated_token_ids.begin(), first.generated_token_ids.end());
    const ginfer::GenerationResult appended =
        engine.generate(engine.prepare_tokens(std::move(prompt)), prefix_options(true));
    const std::uint32_t expected_reuse =
        static_cast<std::uint32_t>(kWrappedPromptTokens + first.generated_token_ids.size() - 1U);
    if (appended.generated_token_ids.size() != 1 ||
        appended.reused_prompt_tokens != expected_reuse ||
        appended.prefix_reuse_path != ginfer::PrefixReusePath::AppendAtFrontier) {
        std::cerr << "Muse DFlash rejected its exact wrapped append frontier: reused="
                  << appended.reused_prompt_tokens << '\n';
        return 1;
    }

    std::vector<ginfer::TokenId> no_identity = protocol_prompt(kWrappedPromptTokens + 4U);
    const ginfer::GenerationResult reset = engine.generate(
        engine.prepare_tokens(std::move(no_identity), false), prefix_options(true));
    if (reset.generated_token_ids.size() != 1 || reset.reused_prompt_tokens != 0 ||
        reset.prefix_reuse_path != ginfer::PrefixReusePath::FullReset) {
        std::cerr << "Muse ignored allow_prefix_identity=false: reused="
                  << reset.reused_prompt_tokens << '\n';
        return 1;
    }
    return 0;
}

int exercise_dflash_execution(ginfer::Engine& engine) {
    ginfer::PromptInput input;
    ginfer::ChatMessage user;
    user.role = ginfer::ChatRole::User;
    user.parts.push_back(ginfer::MessagePart{.kind = ginfer::MessagePartKind::Text,
                                             .text = "Say hello in one sentence.",
                                             .media = {}});
    input.messages.push_back(std::move(user));

    ginfer::RequestOptions options        = greedy_options(false, 3);
    options.stop.include_model_defaults = true;
    const ginfer::GenerationResult result =
        engine.generate(engine.prepare(std::move(input)), options);
    if (result.generated_token_ids.size() < 2 ||
        (result.finish_reason != ginfer::FinishReason::OutputLimit &&
         result.finish_reason != ginfer::FinishReason::StopToken) ||
        !result.speculative.enabled ||
        result.speculative.backend != ginfer::SpeculativeBackend::DFlash ||
        result.speculative.rounds == 0 || result.speculative.drafted_tokens == 0) {
        std::cerr << "Muse short request did not execute and terminate through DFlash\n";
        return 1;
    }
    return 0;
}

int exercise_exact_context_capacity(ginfer::Engine& engine) {
    std::vector<ginfer::TokenId> prompt = protocol_prompt(2304);
    const ginfer::GenerationResult result =
        engine.generate(engine.prepare_tokens(std::move(prompt)), prefix_options(false));
    if (!one_token_terminal(result)) {
        std::cerr << "Muse rejected a one-token generation at exact context capacity\n";
        return 1;
    }
    return 0;
}

} // namespace

int main() {
    const char* artifact = std::getenv("GINFER_MUSE_GLIMMER_30B_WEIGHTS");
    if (artifact == nullptr || *artifact == '\0') {
        std::cout << "skip: GINFER_MUSE_GLIMMER_30B_WEIGHTS is not set\n";
        return 77;
    }

    try {
        const ginfer::artifact::ArtifactIdentity identity =
            ginfer::artifact::Reader(artifact).identity();
        if (identity.model_id != "muse-glimmer-30b" ||
            (identity.weights_id != "groupwise-int" &&
             identity.weights_id != "groupwise-int-dflash-q4" &&
             identity.weights_id != "nvfp4")) {
            std::cerr << "real Muse test received an unsupported artifact identity\n";
            return 1;
        }
        const std::uint64_t expected_weight_bytes =
            identity.weights_id == "nvfp4"
                ? 18'488'472'064ULL
                : identity.weights_id == "groupwise-int-dflash-q4" ? 17'701'999'104ULL
                                                                    : 18'019'114'496ULL;
        ginfer::Engine engine(engine_options(artifact));
        const ginfer::MemorySummary memory = engine.memory_summary();
        if (memory.weights.capacity_bytes != expected_weight_bytes ||
            memory.weights.used_bytes != memory.weights.capacity_bytes ||
            memory.sequence.used_bytes == 0 || memory.workspace.capacity_bytes == 0 ||
            memory.cuda_graph_allowance_bytes != 0) {
            std::cerr << "Muse DFlash Engine has an invalid startup memory summary\n";
            return 1;
        }
        if (const int result = exercise_cyclic_prefix_boundary(engine); result != 0) {
            return result;
        }
        if (const int result = exercise_dflash_execution(engine); result != 0) { return result; }
        return exercise_exact_context_capacity(engine);
    } catch (const std::exception& error) {
        std::cerr << error.what() << '\n';
        return 1;
    }
}
